# Welcome to Jekyll!
#

# Site settings
title: Martin Wiesmüller
description: |
  Software Developer and car-garage application designer
developlangulage: |
  Development - Focus on Javascript, NodeJS, Angular 2
owner: Martin Wiesmüller # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: martin@fa-wiesmueller.de
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mwiesmueller.github.io/" # the base hostname & protocol for your site
languages: ["en", "de"]
exclude_from_localizations: ["js", "images", "css"]
social:
  twitter: https://twitter.com/mwiesmueller
  github: https://github.com/mwiesmueller
  linkedin-square: https://www.linkedin.com/in/martin-wiesm%C3%BCller-784bbbba
  facebook-official: https://facebook.com/martin.wiesmuller.98
  email: mailto:martin@fa-wiesmueller.de
  xing: https://www.xing.com/profile/Martin_Wiesmueller2
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed

gems:
  - jekyll-multiple-languages-plugin
